### ISSUE TITLE
Bump up version to Java 8

### ISSUE THREAD

**Issue by truell20** [HaliteChallenge/Halite#210]

**Comment by hvze** [comment]
Why would you force the requirement of a newer version of java?

**Comment by hyPiRion** [comment]
Afaik Java 7→ Java 8 should effectively be backwards compatible for bots – is there anything in specific that would break in your case (or in general for bot implementations)?

Also, this doesn't mean you have to build and test out stuff with Java 8 locally – I've developed with Java 6 and it works just fine to compile + run Java 7/8 other places.

**Comment by sveri** [comment]
I said it in the forum again, given the style of the problem it would be nice to use lambdas instead of all the for loops.
Also, based on my experience, for a > 200k LOC product that transitioned from 6 to 7 and 8 there was only one change we had to make going from 6 to 7. So I doubt you hit a problem if you use JRE 8 and compile with JDK 6.

**Comment by robertmassaioli** [comment]
I too would appreciate using Java 8 instead just for the streaming library. I'm importing Guava just for that purpose now.

**Comment by truell20** [comment]
Turns out JDK 8 was already in our sandbox :smile:

**Comment by robertmassaioli** [comment]
So, just to confirm, if I was to submit a bot with Java 8 in there then it would "just work"? Sweet!
