### ISSUE TITLE
Support Submission of a Jar

### ISSUE THREAD

**Issue by truell20** [HaliteChallenge/Halite#215]

**Comment by hyPiRion** [comment]
@truell20: What would be the desired functionality here? Here's one possible way:

1. Support `MyBot.jar` as a new language in `compiler.py`.
2. Detect that the uploaded file ends with `.jar` and – instead of unzipping it – move it to the target directory.

Would that be sufficient?

This also makes it possible to embed a `MyBot.jar` in a zip file and submit that, for better or worse.

**Comment by truell20** [comment]
I was planning on the first one.

**Comment by robertmassaioli** [comment]
You can already submit a sources.jar file to the submission location.

**Comment by hyPiRion** [comment]
@robertmassaioli: That's correct, but the effect is that the jar is treated as zip instead of a jar, it's not called via `java -jar ...`.  Adding support for that would be beneficial to support arbitrary JVM languages e.g. Kotlin/Frege/Clojure, although this will also work for Java/Groovy/Scala.

**Comment by robertmassaioli** [comment]
This solves my issue as well because I'm now submitting my code as a JAR. This closes #217
