### ISSUE TITLE
Improve manager `game()` update loop latency

### ISSUE THREAD

**Issue by truell20** [HaliteChallenge/Halite#347]
Taking around 30 sec for each game.

**Comment by Janzert** [comment]
Have you narrowed it down at all to where the time is being spent?

Local testing that otherwise mimics the live user and game counts, but skips the aws upload of replays, completes the call in an average time of about 1 second. If it is the replay upload time I'm not sure what could have caused that to change from earlier on.

**Comment by truell20** [comment]
Added some logging. AWS upload seems to be taking less than a second.

**Comment by truell20** [comment]
I've isolated it to the section under:

> // Update overall rank of everyone

**Comment by truell20** [comment]
Specifically, the latent section is all of the update queries sent to the db after sorting all of the users according to rank.

**Comment by Janzert** [comment]
I'll try and dig into it this evening. The test above was done on the branch with player seed locking, but that should only add more time and effort taken.

One thought, I don't have any inactive users, only 1000 active isRunning=1 users, most with one submission each.
